def cmd_help(Message):
    Message.Chat.SendMessage('>> #tldr for article summarys')
    Message.Chat.SendMessage('>> #stopbot to put BiscuitsBot to sleep')
    Message.Chat.SendMessage('>> #killbot to murder BiscuitsBot')
    Message.Chat.SendMessage('>> RPG COMMANDS BELOW')
    Message.Chat.SendMessage('>> #bottlecap to check your bottlecap balance. (You get 10 per message)')
    Message.Chat.SendMessage('>> #explore to get potential bottlecaps (40% chance for success)')
    Message.Chat.SendMessage('>> #heal to use a stimpack and regain 50 health')
    Message.Chat.SendMessage('>> #stats to check your health and attack')
    Message.Chat.SendMessage('>> #shop to go shopping')
    Message.Chat.SendMessage('>> #buy to buy stuff')
    Message.Chat.SendMessage('>> #leaderboard to check the bottlecap rankings')